SELECT TOP (1000) [UserID]
      ,[FirstName]
      ,[LastName]
      ,[Email]
      ,[Password]
      ,[PasswordHash]
      ,[PasswordSalt]
      ,[Phone]
      ,[ProfileImage]
      ,[Points]
      ,[UserType]
      ,[Uid]    
      ,[ResetToken]
      ,[TokenExpiration]
  FROM [SixthProEcommerce].[dbo].[Users]
